# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/t2m/flame/proprietary//libtime_genoff.so:obj/lib/libtime_genoff.so

# All the blobs
PRODUCT_COPY_FILES += \
vendor/t2m/flame/proprietary//libbt-vendor.so:system/lib/libbt-vendor.so \
vendor/t2m/flame/proprietary//libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
vendor/t2m/flame/proprietary//libgps.utils.so:system/lib/libgps.utils.so \
vendor/t2m/flame/proprietary//libloc_api_v02.so:system/lib/libloc_api_v02.so \
vendor/t2m/flame/proprietary//libloc_core.so:system/lib/libloc_core.so \
vendor/t2m/flame/proprietary//libloc_ds_api.so:system/lib/libloc_ds_api.so \
vendor/t2m/flame/proprietary//libloc_eng.so:system/lib/libloc_eng.so \
vendor/t2m/flame/proprietary//libmdmdetect.so:system/lib/libmdmdetect.so \
vendor/t2m/flame/proprietary//libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
vendor/t2m/flame/proprietary//libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
vendor/t2m/flame/proprietary//libqomx_core.so:system/lib/libqomx_core.so \
vendor/t2m/flame/proprietary//libsigchain.so:system/lib/libsigchain.so \
vendor/t2m/flame/proprietary//libxml2.so:system/lib/libxml2.so \
vendor/t2m/flame/proprietary//libacdbloader.so:system/vendor/lib/libacdbloader.so \
vendor/t2m/flame/proprietary//libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
vendor/t2m/flame/proprietary//libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
vendor/t2m/flame/proprietary//libadiertac.so:system/vendor/lib/libadiertac.so \
vendor/t2m/flame/proprietary//libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
vendor/t2m/flame/proprietary//libadsprpc.so:system/vendor/lib/libadsprpc.so \
vendor/t2m/flame/proprietary//libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
vendor/t2m/flame/proprietary//libaudcal.so:system/vendor/lib/libaudcal.so \
vendor/t2m/flame/proprietary//libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
vendor/t2m/flame/proprietary//libbccQTI.so:system/vendor/lib/libbccQTI.so \
vendor/t2m/flame/proprietary//libbtnv.so:system/vendor/lib/libbtnv.so \
vendor/t2m/flame/proprietary//libC2D2.so:system/vendor/lib/libC2D2.so \
vendor/t2m/flame/proprietary//libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
vendor/t2m/flame/proprietary//libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
vendor/t2m/flame/proprietary//libCB.so:system/vendor/lib/libCB.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
vendor/t2m/flame/proprietary//libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
vendor/t2m/flame/proprietary//libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
vendor/t2m/flame/proprietary//libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
vendor/t2m/flame/proprietary//libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_common.so:system/vendor/lib/libchromatix_ov8825_7853f_common.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_default_video.so:system/vendor/lib/libchromatix_ov8825_7853f_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_7853f_hfr_120fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_7853f_hfr_60fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_7853f_hfr_90fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_liveshot.so:system/vendor/lib/libchromatix_ov8825_7853f_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_preview.so:system/vendor/lib/libchromatix_ov8825_7853f_preview.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_snapshot.so:system/vendor/lib/libchromatix_ov8825_7853f_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_7853f_zsl.so:system/vendor/lib/libchromatix_ov8825_7853f_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
vendor/t2m/flame/proprietary//libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
vendor/t2m/flame/proprietary//libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
vendor/t2m/flame/proprietary//libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
vendor/t2m/flame/proprietary//libcneconn.so:system/vendor/lib/libcneconn.so \
vendor/t2m/flame/proprietary//libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
vendor/t2m/flame/proprietary//libcne.so:system/vendor/lib/libcne.so \
vendor/t2m/flame/proprietary//libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
vendor/t2m/flame/proprietary//libconfigdb.so:system/vendor/lib/libconfigdb.so \
vendor/t2m/flame/proprietary//libdiagbridge.so:system/vendor/lib/libdiagbridge.so \
vendor/t2m/flame/proprietary//libDiagService.so:system/vendor/lib/libDiagService.so \
vendor/t2m/flame/proprietary//libdiag.so:system/vendor/lib/libdiag.so \
vendor/t2m/flame/proprietary//libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
vendor/t2m/flame/proprietary//libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
vendor/t2m/flame/proprietary//libdpmframework.so:system/vendor/lib/libdpmframework.so \
vendor/t2m/flame/proprietary//libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
vendor/t2m/flame/proprietary//libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
vendor/t2m/flame/proprietary//libdrmfs.so:system/vendor/lib/libdrmfs.so \
vendor/t2m/flame/proprietary//libdrmtime.so:system/vendor/lib/libdrmtime.so \
vendor/t2m/flame/proprietary//libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
vendor/t2m/flame/proprietary//libdsucsd.so:system/vendor/lib/libdsucsd.so \
vendor/t2m/flame/proprietary//libdsutils.so:system/vendor/lib/libdsutils.so \
vendor/t2m/flame/proprietary//libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
vendor/t2m/flame/proprietary//libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
vendor/t2m/flame/proprietary//libgeofence.so:system/vendor/lib/libgeofence.so \
vendor/t2m/flame/proprietary//libgsl.so:system/vendor/lib/libgsl.so \
vendor/t2m/flame/proprietary//libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
vendor/t2m/flame/proprietary//libidl.so:system/vendor/lib/libidl.so \
vendor/t2m/flame/proprietary//libimage-jpeg-enc-omx-comp.so:system/vendor/lib/libimage-jpeg-enc-omx-comp.so \
vendor/t2m/flame/proprietary//libimage-omx-common.so:system/vendor/lib/libimage-omx-common.so \
vendor/t2m/flame/proprietary//libimscamera_jni.so:system/vendor/lib/libimscamera_jni.so \
vendor/t2m/flame/proprietary//libimsmedia_jni.so:system/vendor/lib/libimsmedia_jni.so \
vendor/t2m/flame/proprietary//libizat_core.so:system/vendor/lib/libizat_core.so \
vendor/t2m/flame/proprietary//libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
vendor/t2m/flame/proprietary//libjpegehw.so:system/vendor/lib/libjpegehw.so \
vendor/t2m/flame/proprietary//liblbs_core.so:system/vendor/lib/liblbs_core.so \
vendor/t2m/flame/proprietary//libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
vendor/t2m/flame/proprietary//libloc2jnibridge.so:system/vendor/lib/libloc2jnibridge.so \
vendor/t2m/flame/proprietary//liblocationservice.so:system/vendor/lib/liblocationservice.so \
vendor/t2m/flame/proprietary//libloc_ext.so:system/vendor/lib/libloc_ext.so \
vendor/t2m/flame/proprietary//libloc_xtra.so:system/vendor/lib/libloc_xtra.so \
vendor/t2m/flame/proprietary//liblowi_client.so:system/vendor/lib/liblowi_client.so \
vendor/t2m/flame/proprietary//libmasc.so:system/vendor/lib/libmasc.so \
vendor/t2m/flame/proprietary//libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
vendor/t2m/flame/proprietary//libmm-abl.so:system/vendor/lib/libmm-abl.so \
vendor/t2m/flame/proprietary//libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
vendor/t2m/flame/proprietary//libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
vendor/t2m/flame/proprietary//libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
vendor/t2m/flame/proprietary//libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
vendor/t2m/flame/proprietary//libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
vendor/t2m/flame/proprietary//libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
vendor/t2m/flame/proprietary//libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
vendor/t2m/flame/proprietary//libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
vendor/t2m/flame/proprietary//libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
vendor/t2m/flame/proprietary//libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
vendor/t2m/flame/proprietary//libmmcamera_hi258.so:system/vendor/lib/libmmcamera_hi258.so \
vendor/t2m/flame/proprietary//libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
vendor/t2m/flame/proprietary//libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
vendor/t2m/flame/proprietary//libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
vendor/t2m/flame/proprietary//libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
vendor/t2m/flame/proprietary//libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
vendor/t2m/flame/proprietary//libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
vendor/t2m/flame/proprietary//libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
vendor/t2m/flame/proprietary//libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
vendor/t2m/flame/proprietary//libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
vendor/t2m/flame/proprietary//libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
vendor/t2m/flame/proprietary//libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
vendor/t2m/flame/proprietary//libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
vendor/t2m/flame/proprietary//libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
vendor/t2m/flame/proprietary//libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
vendor/t2m/flame/proprietary//libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
vendor/t2m/flame/proprietary//libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
vendor/t2m/flame/proprietary//libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
vendor/t2m/flame/proprietary//libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
vendor/t2m/flame/proprietary//libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
vendor/t2m/flame/proprietary//libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
vendor/t2m/flame/proprietary//libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
vendor/t2m/flame/proprietary//libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
vendor/t2m/flame/proprietary//libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
vendor/t2m/flame/proprietary//libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
vendor/t2m/flame/proprietary//libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
vendor/t2m/flame/proprietary//libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
vendor/t2m/flame/proprietary//libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
vendor/t2m/flame/proprietary//libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
vendor/t2m/flame/proprietary//libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
vendor/t2m/flame/proprietary//libmmipl.so:system/vendor/lib/libmmipl.so \
vendor/t2m/flame/proprietary//libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
vendor/t2m/flame/proprietary//libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
vendor/t2m/flame/proprietary//libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
vendor/t2m/flame/proprietary//libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
vendor/t2m/flame/proprietary//libmmi.so:system/vendor/lib/libmmi.so \
vendor/t2m/flame/proprietary//libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
vendor/t2m/flame/proprietary//libmmosal.so:system/vendor/lib/libmmosal.so \
vendor/t2m/flame/proprietary//libmmparser.so:system/vendor/lib/libmmparser.so \
vendor/t2m/flame/proprietary//libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
vendor/t2m/flame/proprietary//libmmQSM.so:system/vendor/lib/libmmQSM.so \
vendor/t2m/flame/proprietary//libmmstillomx.so:system/vendor/lib/libmmstillomx.so \
vendor/t2m/flame/proprietary//libmsapm_jni.so:system/vendor/lib/libmsapm_jni.so \
vendor/t2m/flame/proprietary//libnetmgr.so:system/vendor/lib/libnetmgr.so \
vendor/t2m/flame/proprietary//libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
vendor/t2m/flame/proprietary//liboemcamera.so:system/vendor/lib/liboemcamera.so \
vendor/t2m/flame/proprietary//libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
vendor/t2m/flame/proprietary//libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
vendor/t2m/flame/proprietary//libOmxIttiamVdec.so:system/vendor/lib/libOmxIttiamVdec.so \
vendor/t2m/flame/proprietary//libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
vendor/t2m/flame/proprietary//libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
vendor/t2m/flame/proprietary//libOpenCL.so:system/vendor/lib/libOpenCL.so \
vendor/t2m/flame/proprietary//libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
vendor/t2m/flame/proprietary//libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
vendor/t2m/flame/proprietary//libqdi.so:system/vendor/lib/libqdi.so \
vendor/t2m/flame/proprietary//libqdp.so:system/vendor/lib/libqdp.so \
vendor/t2m/flame/proprietary//libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
vendor/t2m/flame/proprietary//libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
vendor/t2m/flame/proprietary//libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
vendor/t2m/flame/proprietary//libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
vendor/t2m/flame/proprietary//libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
vendor/t2m/flame/proprietary//libqmi_csvt_srvc.so:system/vendor/lib/libqmi_csvt_srvc.so \
vendor/t2m/flame/proprietary//libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
vendor/t2m/flame/proprietary//libqmiservices.so:system/vendor/lib/libqmiservices.so \
vendor/t2m/flame/proprietary//libqmi.so:system/vendor/lib/libqmi.so \
vendor/t2m/flame/proprietary//libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
vendor/t2m/flame/proprietary//libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
vendor/t2m/flame/proprietary//libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
vendor/t2m/flame/proprietary//libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
vendor/t2m/flame/proprietary//libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
vendor/t2m/flame/proprietary//libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
vendor/t2m/flame/proprietary//libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
vendor/t2m/flame/proprietary//libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
vendor/t2m/flame/proprietary//librpmb.so:system/vendor/lib/librpmb.so \
vendor/t2m/flame/proprietary//librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
vendor/t2m/flame/proprietary//librs_adreno.so:system/vendor/lib/librs_adreno.so \
vendor/t2m/flame/proprietary//libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
vendor/t2m/flame/proprietary//libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
vendor/t2m/flame/proprietary//libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
vendor/t2m/flame/proprietary//libscale.so:system/vendor/lib/libscale.so \
vendor/t2m/flame/proprietary//libSHIMDivxDrm.so:system/vendor/lib/libSHIMDivxDrm.so \
vendor/t2m/flame/proprietary//libsmemlog.so:system/vendor/lib/libsmemlog.so \
vendor/t2m/flame/proprietary//libssd.so:system/vendor/lib/libssd.so \
vendor/t2m/flame/proprietary//libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
vendor/t2m/flame/proprietary//libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
vendor/t2m/flame/proprietary//libsurround_proc.so:system/vendor/lib/libsurround_proc.so \
vendor/t2m/flame/proprietary//libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
vendor/t2m/flame/proprietary//libthermalclient.so:system/vendor/lib/libthermalclient.so \
vendor/t2m/flame/proprietary//libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
vendor/t2m/flame/proprietary//libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
vendor/t2m/flame/proprietary//libTimeService.so:system/vendor/lib/libTimeService.so \
vendor/t2m/flame/proprietary//libulp2.so:system/vendor/lib/libulp2.so \
vendor/t2m/flame/proprietary//libvendorconn.so:system/vendor/lib/libvendorconn.so \
vendor/t2m/flame/proprietary//libwifiscanner.so:system/vendor/lib/libwifiscanner.so \
vendor/t2m/flame/proprietary//libwqe.so:system/vendor/lib/libwqe.so \
vendor/t2m/flame/proprietary//libxml.so:system/vendor/lib/libxml.so \
vendor/t2m/flame/proprietary//libxtadapter.so:system/vendor/lib/libxtadapter.so \
vendor/t2m/flame/proprietary//libxt_native.so:system/vendor/lib/libxt_native.so \
vendor/t2m/flame/proprietary//libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
vendor/t2m/flame/proprietary//libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so \
vendor/t2m/flame/proprietary//adsprpcd:system/bin/adsprpcd \
vendor/t2m/flame/proprietary//audiod:system/bin/audiod \
vendor/t2m/flame/proprietary//charger_monitor:system/bin/charger_monitor \
vendor/t2m/flame/proprietary//fm_qsoc_patches:system/bin/fm_qsoc_patches \
vendor/t2m/flame/proprietary//fmconfig:system/bin/fmconfig \
vendor/t2m/flame/proprietary//hci_qcomm_init:system/bin/hci_qcomm_init \
vendor/t2m/flame/proprietary//location-mq:system/bin/location-mq \
vendor/t2m/flame/proprietary//lowi-server:system/bin/lowi-server \
vendor/t2m/flame/proprietary//mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
vendor/t2m/flame/proprietary//mpdecision:system/bin/mpdecision \
vendor/t2m/flame/proprietary//netmgrd:system/bin/netmgrd \
vendor/t2m/flame/proprietary//ptt_socket_app:system/bin/ptt_socket_app \
vendor/t2m/flame/proprietary//qcom-system-daemon:system/bin/qcom-system-daemon \
vendor/t2m/flame/proprietary//qmuxd:system/bin/qmuxd \
vendor/t2m/flame/proprietary//qseecomd:system/bin/qseecomd \
vendor/t2m/flame/proprietary//radish:system/bin/radish \
vendor/t2m/flame/proprietary//rfs_access:system/bin/rfs_access \
vendor/t2m/flame/proprietary//rmt_storage:system/bin/rmt_storage \
vendor/t2m/flame/proprietary//thermal-engine:system/bin/thermal-engine \
vendor/t2m/flame/proprietary//time_daemon:system/bin/time_daemon \
vendor/t2m/flame/proprietary//trace_util:system/bin/trace_util \
vendor/t2m/flame/proprietary//vold:system/bin/vold \
vendor/t2m/flame/proprietary//xtwifi-client:system/bin/xtwifi-client \
vendor/t2m/flame/proprietary//xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
vendor/t2m/flame/proprietary/hw/audio.primary.msm8610.so:system/lib/hw/audio.primary.msm8610.so \
vendor/t2m/flame/proprietary/hw/camera.msm8610.so:system/lib/hw/camera.msm8610.so \
vendor/t2m/flame/proprietary/hw/gps.default.so:system/lib/hw/gps.default.so \
vendor/t2m/flame/proprietary/hw/sensors.msm8610.so:system/lib/hw/sensors.msm8610.so \
vendor/t2m/flame/proprietary/etc/lowi.conf:system/etc/lowi.conf \
vendor/t2m/flame/proprietary/etc/mixer_paths.xml:system/etc/mixer_paths.xml \
vendor/t2m/flame/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
vendor/t2m/flame/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
vendor/t2m/flame/proprietary/nfc/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
vendor/t2m/flame/proprietary/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
vendor/t2m/flame/proprietary/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
vendor/t2m/flame/proprietary/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
vendor/t2m/flame/proprietary/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
vendor/t2m/flame/proprietary/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
vendor/t2m/flame/proprietary/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
vendor/t2m/flame/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
vendor/t2m/flame/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
vendor/t2m/flame/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
vendor/t2m/flame/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
vendor/t2m/flame/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
vendor/t2m/flame/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
vendor/t2m/flame/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
vendor/t2m/flame/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
vendor/t2m/flame/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
